name: Metrics
on:
  schedule: [{cron: "0 3 * * 6"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: marmig0404
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_traffic: yes
